run:
  timeout: 2m
  modules-download-mode: readonly

linters-settings:
  govet:
    # Disable shadow checking for now as it creates too many false positives
    enable:
      - assign
      - atomic
      - bools
      - buildtag
      - cgocall
      - composites
      - copylocks
      - httpresponse
      - loopclosure
      - lostcancel
      - nilfunc
      - printf
      - shift
      - stdmethods
      - structtag
      - tests
      - unmarshal
      - unreachable
      - unsafeptr
      - unusedresult
    disable:
      - shadow
  gofmt:
    simplify: true

linters:
  enable:
    - gosimple
    - govet
    - staticcheck
    - typecheck
    - gofmt
    - goimports
  disable:
    - errcheck      # Too many issues to fix right now
    - ineffassign    # Non-critical
    - unused         # Many false positives
    - misspell       # Non-critical
    - goconst        # Non-critical code quality
    - revive         # Non-critical style issues
    - gocyclo
    - dupl
    - maligned
    - prealloc
    - funlen
    - lll
    - gci

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    - path: vendor/
      linters:
        - all
    - text: "G404: Use of weak random number generator"
      linters:
        - gosec