repos:
  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: go fmt
        language: system
        files: \.go$
        pass_filenames: false
        
      - id: go-vet
        name: go vet
        entry: go vet
        language: system
        files: \.go$
        pass_filenames: false
        args: [./...]
        
      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint run
        language: system
        files: \.go$
        pass_filenames: false