ALTER TABLE routes ADD COLUMN path TEXT;
ALTER TABLE routes ADD COLUMN certificate_id INTEGER REFERENCES certificates(id);
ALTER TABLE routes ADD COLUMN proxy_config TEXT; -- JSON
ALTER TABLE routes ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP;