name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.24', '1.23']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        cache: true
    
    - name: Install govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@latest
    
    - name: Format and Vet
      run: make fmt vet
    
    - name: Lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: latest
        args: --timeout=2m
    
    - name: Test with Race Detection
      run: go test -race -short ./...
    
    - name: Vulnerability Check
      run: govulncheck ./...
    
    - name: Build
      run: make build
    
    - name: Pack Static Binary
      run: make pack